image: microsoft/dotnet:latest

stages:
  - build
  - test
  - deploy


build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  script:
    - dotnet test travel-booking.tests

deploy:dummy
  stage: deploy
  script: 
    - echo 'hello'
  when: manual